version: '3'

services:
  chatdemo:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: chat_demo_dev
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: chat_demo_dev
      PGPORT: 5432
    command: ./entrypoint.sh
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:11.2
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: chat_demo_dev
      PGPORT: 5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata: